dataset:  DrugBank
task: binary 
category: DDI
entry1_file: ./dataset/DrugBank/drug/processed/data.pt
entry2_file: ./dataset/DrugBank/drug/processed/data.pt
entry1_seq_file: ./dataset/DrugBank/drug/drug.csv
pair_file: ./dataset/DrugBank/binary_1vs1/entry_pairs.csv
label_file: ./dataset/DrugBank/binary_1vs1/pair_labels.csv
save_folder: ./output/mol_conf/RGIN/DrugBank/binary_1vs1/one_cluster/
split_strategy: whole_cluster_sampling
gconv_ckpt: ./model_checkpoints/molconf_molconf_RGIN_epoch_20_layers_4_random/last.ckpt
lin_eval: False
model_type: deepdrug
gpus: 0
num_out_dim: 1
n_layers: 4
n_confs: 0
g_conv: RGIN
lr: 0.0001