alpha_l: 2
concat_hidden: false
decoder_type: deepgcn
drop_edge_rate: 0.0
encoder_type: deepgcn
in_dim: 119
in_edge_channel: 11
loss_fn: mse
lr: 0.001
mask_rate: 0.3
mid_edge_channel: 128
my_logging: false
nhead: 4
nhead_out: 2
num_hidden: 128
num_layers: 2
replace_rate: 0.1
scheduler_ReduceLROnPlateau_tracking: mse
verbose: true
