dataset:  TWOSIDES
task: binary 
category: DDI
entry1_file: ./dataset/TWOSIDES/drug/processed/data.pt
entry2_file: ./dataset/TWOSIDES/drug/processed/data.pt
entry1_seq_file: ./dataset/TWOSIDES/drug/drug.csv
pair_file: ./dataset/TWOSIDES/binary_1vs1/entry_pairs.csv
label_file: ./dataset/TWOSIDES/binary_1vs1/pair_labels.csv
save_folder: ./output/CLR/RGCN/TWOSIDES/binary_1vs1/one_cluster/
split_strategy: whole_cluster_sampling
gconv_ckpt: ./model_checkpoints/clr_epoch_RGCN_20_layers_4_random/last.ckpt
lin_eval: False
model_type: deepdrug
gpus: 0
num_out_dim: 1
n_layers: 4
g_conv: RGCN
lr: 0.0001