dataset:  TWOSIDES
task: binary 
category: DDI
entry1_file: ./dataset/TWOSIDES/drug/processed/data.pt
entry2_file: ./dataset/TWOSIDES/drug/processed/data.pt
entry1_seq_file: ./dataset/TWOSIDES/drug/drug.csv
entry2_seq_file: ./dataset/TWOSIDES/drug/drug.csv
pair_file: ./dataset/TWOSIDES/binary_1vs1/entry_pairs.csv
label_file: ./dataset/TWOSIDES/binary_1vs1/pair_labels.csv
save_folder: ./output/deepdrug/TWOSIDES/binary_1vs1/random/
split_strategy: random
lin_eval: False
model_type: deepdrug
gpus: 0
num_out_dim: 1
n_layers: 22
n_confs: 0